name: template
description: A Template Projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Localization support
    sdk: flutter
  #Main packages
  get_it: ^7.2.0 #for DI
  get: ^4.6.5 # for snackbar, dialog, operations without context
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.6
  rxdart: ^0.27.7
  dartz: ^0.10.1
  riverpod: ^2.2.0 #state management
  hooks_riverpod: ^2.2.0 #state management
  flutter_bloc: ^8.1.2
  dio: ^5.0.1
  flutter_screenutil: ^5.6.1 #responsiveness
  shared_preferences: ^2.0.18
  flutter_svg: ^2.0.2
  pin_code_fields: ^7.4.0
  introduction_screen: ^3.1.1
  dots_indicator: ^2.1.0
  cached_network_image: ^3.2.3
  readmore: ^2.2.0
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  #Helper Packages
  google_maps_flutter: ^2.2.4
  fl_chart: ^0.61.0
  get_storage: ^2.0.3
  image_picker: ^0.8.6+3
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^4.0.5
  url_launcher: ^6.1.10
  flutter_gen: ^5.2.0
  carousel_slider: ^4.2.1
  flutter_cupertino_datetime_picker: ^3.0.0
  path_provider: ^2.0.13
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  overlay_support: ^2.1.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^20.4.51
  animations: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  auto_route_generator: ^5.0.3
  build_runner: null
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - languages/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500        
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700